// Header pictures
export { default as Logo } from './logo.svg'
export { default as SearchIcon } from './search-icon.svg'
export { default as EyeIcon } from './eye.svg'
export { default as LikeIcon } from './like.svg'
export { default as CompareIcon } from './compare.svg'
export { default as CartIcon } from './cart.svg'
export { default as ProfileIcon } from './profile.svg'
export { default as Line14 } from './Line14.svg'
export { default as catalogIcon } from './catalog-icon.svg'
